export enum Currency {
  ALEX = 'age000-governance-token',
  USDA = 'token-wusda',
  STX = 'token-wstx',
  BANANA = 'token-wban',
  XBTC = 'token-wbtc',
  DIKO = 'token-wdiko',
  SLIME = 'token-wslm',
  XUSD = 'token-wxusd',
  MIA = 'token-wmia',
  NYCC = 'token-wnycc',
  CORGI = 'token-wcorgi',
  ATALEXV2 = 'auto-alex-v2',
  sUSDT = 'token-susdt',
  VIBES = 'token-wvibes',
  BRC20_DB20 = 'brc20-db20',
  aBTC = 'token-abtc',
  sLUNR = 'token-slunr',
  BRC20_CHAX = 'brc20-chax',
  LEO = "token-wleo",
  MEGA = "token-wmega-v2",
  GUS = "token-wgus",
  BRC20_ORDG = "brc20-ordg",
  BRC20_ORMM = "brc20-ormm",
}
